name: ci
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install base tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff bandit pytest
      - name: Lint
        run: |
          ruff check .
          bandit -r . || true
      # TODO: Tighten tests
      - name: Test
        run: |
          pytest -q || true